//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonDBExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dragon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Kills { get; set; }
    }
}
